-- ========================================
-- PERGUNTA 1: Valor Total de Penalidades por Estado, Cidade e Bairro
-- ========================================
-- "Identificar o valor total de penalidades aplicadas nos veículos 
--  agrupado por Estado, Cidade e Bairro"
-- ========================================

CREATE OR REPLACE VIEW VW_PENALIDADES_POR_LOCALIZACAO AS
SELECT 
    -- Agrupamento EXATO conforme solicitado
    l.NM_ESTADO,
    l.SG_ESTADO,
    l.NM_CIDADE,
    l.NM_BAIRRO,
    
    -- RESPOSTA PRINCIPAL: Valor Total de Penalidades
    SUM(f.VL_MULTA) AS VL_TOTAL_PENALIDADES,
    
    -- Métricas Adicionais
    COUNT(*) AS QTD_TOTAL_INFRACOES,
    COUNT(DISTINCT f.SK_ID_VEICULO) AS QTD_VEICULOS_MULTADOS,
    AVG(f.VL_MULTA) AS VL_MEDIO_PENALIDADES,
    MIN(f.VL_MULTA) AS VL_MIN_PENALIDADE,
    MAX(f.VL_MULTA) AS VL_MAX_PENALIDADE,
    
    -- Métricas Complementares
    SUM(f.QT_INFRACOES) AS TOTAL_INFRACOES_REGISTRADAS,
    AVG(f.VL_VELOCIDADE_REGISTRADA) AS VELOCIDADE_MEDIA_INFRATORES,
    AVG(f."VL_VELOCIDADE_PERMITIDA_KM/H") AS VELOCIDADE_MEDIA_PERMITIDA,
    
    -- Informações de Contexto
    COUNT(DISTINCT l.NM_LOGRADOURO) AS QTD_LOGRADOUROS,
    COUNT(DISTINCT f.SK_ID_RADAR) AS QTD_RADARES_ATIVOS,
    
    -- Rankings
    RANK() OVER (ORDER BY SUM(f.VL_MULTA) DESC) AS RANKING_NACIONAL,
    RANK() OVER (PARTITION BY l.NM_ESTADO ORDER BY SUM(f.VL_MULTA) DESC) AS RANKING_ESTADUAL,
    
    -- Percentuais
    ROUND(SUM(f.VL_MULTA) * 100.0 / SUM(SUM(f.VL_MULTA)) OVER (), 2) AS PERCENTUAL_NACIONAL
    
FROM 
    TB_FATO_TRAFEGO f
    INNER JOIN TB_DIM_LOCAL l ON f.SK_ID_LOCAL = l.SK_ID_LOCAL
WHERE 
    f.ST_INFRACOES = 'ATIVO'
    AND f.ST_REGISTRO_ATUAL = 'A'
    AND l.ST_REGISTRO_ATUAL = 'A'
GROUP BY 
    l.NM_ESTADO,
    l.SG_ESTADO,
    l.NM_CIDADE,
    l.NM_BAIRRO
ORDER BY 
    VL_TOTAL_PENALIDADES DESC;

COMMENT ON TABLE VW_PENALIDADES_POR_LOCALIZACAO IS 
'Valor total de penalidades agrupado por Estado, Cidade e Bairro (Pergunta Executiva 1)';

-- ========================================
-- TESTES
-- ========================================

-- Teste 1: Consulta básica conforme a pergunta
SELECT 
    NM_ESTADO,
    NM_CIDADE,
    NM_BAIRRO,
    VL_TOTAL_PENALIDADES
FROM VW_PENALIDADES_POR_LOCALIZACAO
ORDER BY VL_TOTAL_PENALIDADES DESC
FETCH FIRST 20 ROWS ONLY;

-- Teste 2: Por Estado
SELECT 
    NM_ESTADO,
    SUM(VL_TOTAL_PENALIDADES) AS TOTAL_ESTADO,
    COUNT(*) AS QTD_BAIRROS
FROM VW_PENALIDADES_POR_LOCALIZACAO
GROUP BY NM_ESTADO
ORDER BY TOTAL_ESTADO DESC;

-- Teste 3: Por Cidade
SELECT 
    NM_ESTADO,
    NM_CIDADE,
    SUM(VL_TOTAL_PENALIDADES) AS TOTAL_CIDADE,
    COUNT(*) AS QTD_BAIRROS
FROM VW_PENALIDADES_POR_LOCALIZACAO
GROUP BY NM_ESTADO, NM_CIDADE
ORDER BY TOTAL_CIDADE DESC;

-- Teste 4: Validação - Deve ter 1 linha por bairro
SELECT 
    NM_CIDADE,
    NM_BAIRRO,
    COUNT(*) AS QTD_LINHAS
FROM VW_PENALIDADES_POR_LOCALIZACAO
GROUP BY NM_CIDADE, NM_BAIRRO
HAVING COUNT(*) > 1;  -- Não deve retornar nada!



-- ========================================
-- PERGUNTA 2: Penalidades por Hora, Dia da Semana, Mês e Ano
-- ========================================

CREATE OR REPLACE VIEW VW_PENALIDADES_POR_TEMPO AS
SELECT 
    -- Agrupamento conforme solicitado
    t.NR_ANO,
    t.NR_MES,
    t.DS_MES,
    t.DS_DIA_SEMANA,
    t.NR_DIA_SEMANA,
    t.NR_HORA,
    
    -- Informação sobre Feriado (IMPORTANTE para análise)
    t.DS_DIA_UTIL_FERIADO,
    t.DS_FIM_SEMANA,
    
    -- RESPOSTA: Quantidade Total de Penalidades
    COUNT(*) AS QTD_TOTAL_PENALIDADES,
    
    -- Métricas Adicionais
    SUM(f.VL_MULTA) AS VL_TOTAL_MULTAS,
    AVG(f.VL_MULTA) AS VL_MEDIO_MULTAS,
    SUM(f.QT_INFRACOES) AS TOTAL_INFRACOES,
    COUNT(DISTINCT f.SK_ID_VEICULO) AS QTD_VEICULOS_DISTINTOS,
    AVG(f.VL_VELOCIDADE_REGISTRADA) AS VELOCIDADE_MEDIA,
    
    -- Informações Complementares de Tempo
    t.NR_SEMESTRE,
    t.DS_SEMESTRE,
    t.NR_TRIMESTRE,
    t.DS_TRIMESTRE,
    
    -- Rankings
    RANK() OVER (ORDER BY COUNT(*) DESC) AS RANKING_GERAL,
    RANK() OVER (PARTITION BY t.NR_ANO ORDER BY COUNT(*) DESC) AS RANKING_ANO,
    
    -- Percentuais
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (), 2) AS PERCENTUAL_TOTAL
    
FROM 
    TB_FATO_TRAFEGO f
    INNER JOIN TB_DIM_TEMPO t ON f.SK_ID_TEMPO = t.SK_ID_TEMPO
WHERE 
    f.ST_INFRACOES = 'ATIVO'
    AND f.ST_REGISTRO_ATUAL = 'A'
    AND t.ST_REGISTRO_ATUAL = 'A'
GROUP BY 
    t.NR_ANO,
    t.NR_MES,
    t.DS_MES,
    t.DS_DIA_SEMANA,
    t.NR_DIA_SEMANA,
    t.NR_HORA,
    t.DS_DIA_UTIL_FERIADO,
    t.DS_FIM_SEMANA,
    t.NR_SEMESTRE,
    t.DS_SEMESTRE,
    t.NR_TRIMESTRE,
    t.DS_TRIMESTRE
ORDER BY 
    t.NR_ANO DESC,
    t.NR_MES DESC,
    t.NR_HORA;

COMMENT ON TABLE VW_PENALIDADES_POR_TEMPO IS 
'Quantidade de penalidades por hora, dia da semana, mês e ano, incluindo feriados (Pergunta 2)';

-- ========================================
-- TESTES
-- ========================================

-- Teste 1: Consulta básica
SELECT NR_ANO, NR_MES, DS_MES, NR_HORA, DS_DIA_SEMANA, DS_DIA_UTIL_FERIADO, QTD_TOTAL_PENALIDADES
FROM VW_PENALIDADES_POR_TEMPO
ORDER BY QTD_TOTAL_PENALIDADES DESC
FETCH FIRST 20 ROWS ONLY;

-- Teste 2: Comparação Feriado vs Dia Útil
SELECT 
    DS_DIA_UTIL_FERIADO,
    SUM(QTD_TOTAL_PENALIDADES) AS TOTAL_PENALIDADES,
    ROUND(AVG(QTD_TOTAL_PENALIDADES), 2) AS MEDIA_PENALIDADES
FROM VW_PENALIDADES_POR_TEMPO
GROUP BY DS_DIA_UTIL_FERIADO
ORDER BY TOTAL_PENALIDADES DESC;

-- Teste 3: Por Hora do Dia
SELECT 
    NR_HORA,
    SUM(QTD_TOTAL_PENALIDADES) AS TOTAL_PENALIDADES
FROM VW_PENALIDADES_POR_TEMPO
GROUP BY NR_HORA
ORDER BY NR_HORA;

-- Teste 4: Por Dia da Semana
SELECT 
    DS_DIA_SEMANA,
    DS_FIM_SEMANA,
    SUM(QTD_TOTAL_PENALIDADES) AS TOTAL_PENALIDADES
FROM VW_PENALIDADES_POR_TEMPO
GROUP BY DS_DIA_SEMANA, NR_DIA_SEMANA, DS_FIM_SEMANA
ORDER BY NR_DIA_SEMANA;

-- Teste 5: Por Mês
SELECT 
    NR_ANO,
    NR_MES,
    DS_MES,
    SUM(QTD_TOTAL_PENALIDADES) AS TOTAL_PENALIDADES
FROM VW_PENALIDADES_POR_TEMPO
GROUP BY NR_ANO, NR_MES, DS_MES
ORDER BY NR_ANO DESC, NR_MES;



-- ========================================
-- PERGUNTA 3: Penalidades por Quadrante
-- ========================================

CREATE OR REPLACE VIEW VW_PENALIDADES_POR_QUADRANTE AS
SELECT 
    l.NR_QUADRANTE,
    l.NM_ESTADO,
    l.SG_ESTADO,
    l.NM_CIDADE,
    
    -- RESPOSTA: Maior número de penalidades
    COUNT(*) AS QTD_PENALIDADES,
    
    -- Métricas Adicionais
    SUM(f.VL_MULTA) AS VL_TOTAL_MULTAS,
    AVG(f.VL_MULTA) AS VL_MEDIO_MULTAS,
    COUNT(DISTINCT f.SK_ID_VEICULO) AS QTD_VEICULOS_DISTINTOS,
    COUNT(DISTINCT l.NM_BAIRRO) AS QTD_BAIRROS,
    COUNT(DISTINCT l.SK_ID_LOCAL) AS QTD_LOCAIS_DISTINTOS,
    SUM(f.QT_INFRACOES) AS TOTAL_INFRACOES,
    AVG(f.VL_VELOCIDADE_REGISTRADA) AS VELOCIDADE_MEDIA,
    
    -- Rankings
    RANK() OVER (ORDER BY COUNT(*) DESC) AS RANKING_GERAL,
    RANK() OVER (PARTITION BY l.NR_QUADRANTE ORDER BY COUNT(*) DESC) AS RANKING_POR_QUADRANTE,
    
    -- Percentuais
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (), 2) AS PERCENTUAL_TOTAL,
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (PARTITION BY l.NR_QUADRANTE), 2) AS PERCENTUAL_QUADRANTE
    
FROM 
    TB_FATO_TRAFEGO f
    INNER JOIN TB_DIM_LOCAL l ON f.SK_ID_LOCAL = l.SK_ID_LOCAL
WHERE 
    f.ST_INFRACOES = 'ATIVO'
    AND f.ST_REGISTRO_ATUAL = 'A'
    AND l.ST_REGISTRO_ATUAL = 'A'
GROUP BY 
    l.NR_QUADRANTE,
    l.NM_ESTADO,
    l.SG_ESTADO,
    l.NM_CIDADE
ORDER BY 
    l.NR_QUADRANTE,
    QTD_PENALIDADES DESC;

COMMENT ON TABLE VW_PENALIDADES_POR_QUADRANTE IS 
'Regiões com maior número de penalidades por quadrante (1, 2, 3, 4) - Pergunta 3';

-- ========================================
-- TESTES
-- ========================================

-- Teste 1: Resumo por Quadrante
SELECT 
    NR_QUADRANTE,
    SUM(QTD_PENALIDADES) AS TOTAL_PENALIDADES,
    SUM(VL_TOTAL_MULTAS) AS TOTAL_MULTAS,
    COUNT(DISTINCT NM_CIDADE) AS QTD_CIDADES
FROM VW_PENALIDADES_POR_QUADRANTE
GROUP BY NR_QUADRANTE
ORDER BY NR_QUADRANTE;

-- Teste 2: Top 5 Cidades por Quadrante
SELECT NR_QUADRANTE, NM_CIDADE, QTD_PENALIDADES, RANKING_POR_QUADRANTE
FROM VW_PENALIDADES_POR_QUADRANTE
WHERE RANKING_POR_QUADRANTE <= 5
ORDER BY NR_QUADRANTE, RANKING_POR_QUADRANTE;

-- Teste 3: Consulta Completa
SELECT NR_QUADRANTE, NM_ESTADO, NM_CIDADE, QTD_PENALIDADES, VL_TOTAL_MULTAS
FROM VW_PENALIDADES_POR_QUADRANTE
ORDER BY QTD_PENALIDADES DESC
FETCH FIRST 20 ROWS ONLY;


-- ========================================
-- PERGUNTA 4: Volume de Veículos e Velocidade por Hora
-- ========================================

CREATE OR REPLACE VIEW VW_VOLUME_VELOCIDADE_POR_HORA AS
SELECT 
    t.DT_REFERENCIA,
    t.NR_ANO,
    t.NR_MES,
    t.NR_DIA_MES,
    t.DS_DIA_SEMANA,
    t.NR_HORA,
    l.NM_ESTADO,
    l.SG_ESTADO,
    l.NM_CIDADE,
    l.NM_BAIRRO,
    
    -- RESPOSTA: Volume de veículos
    SUM(f.QT_VEICULOS) AS VOLUME_TOTAL_VEICULOS,
    
    -- RESPOSTA: Velocidade média
    AVG(f.VL_VELOCIDADE_REGISTRADA) AS VELOCIDADE_MEDIA,
    
    -- Métricas Adicionais
    COUNT(*) AS QTD_REGISTROS,
    AVG(f."VL_VELOCIDADE_PERMITIDA_KM/H") AS VELOCIDADE_MEDIA_PERMITIDA,
    MIN(f.VL_VELOCIDADE_REGISTRADA) AS VELOCIDADE_MIN,
    MAX(f.VL_VELOCIDADE_REGISTRADA) AS VELOCIDADE_MAX,
    SUM(CASE WHEN f.ST_INFRACOES = 'ATIVO' THEN 1 ELSE 0 END) AS QTD_INFRACOES,
    SUM(CASE WHEN f.ST_INFRACOES = 'ATIVO' THEN f.VL_MULTA ELSE 0 END) AS VL_TOTAL_MULTAS,
    
    -- Rankings por Estado, Cidade e Bairro
    RANK() OVER (PARTITION BY t.DT_REFERENCIA, t.NR_HORA ORDER BY SUM(f.QT_VEICULOS) DESC) AS RANKING_HORA,
    RANK() OVER (PARTITION BY l.NM_ESTADO ORDER BY SUM(f.QT_VEICULOS) DESC) AS RANKING_ESTADO,
    RANK() OVER (PARTITION BY l.NM_ESTADO, l.NM_CIDADE ORDER BY SUM(f.QT_VEICULOS) DESC) AS RANKING_CIDADE,
    RANK() OVER (PARTITION BY l.NM_ESTADO, l.NM_CIDADE, l.NM_BAIRRO ORDER BY SUM(f.QT_VEICULOS) DESC) AS RANKING_BAIRRO
    
FROM 
    TB_FATO_TRAFEGO f
    INNER JOIN TB_DIM_TEMPO t ON f.SK_ID_TEMPO = t.SK_ID_TEMPO
    INNER JOIN TB_DIM_LOCAL l ON f.SK_ID_LOCAL = l.SK_ID_LOCAL
WHERE 
    f.ST_REGISTRO_ATUAL = 'A'
    AND t.ST_REGISTRO_ATUAL = 'A'
    AND l.ST_REGISTRO_ATUAL = 'A'
GROUP BY 
    t.DT_REFERENCIA,
    t.NR_ANO,
    t.NR_MES,
    t.NR_DIA_MES,
    t.DS_DIA_SEMANA,
    t.NR_HORA,
    l.NM_ESTADO,
    l.SG_ESTADO,
    l.NM_CIDADE,
    l.NM_BAIRRO
ORDER BY 
    t.DT_REFERENCIA DESC,
    t.NR_HORA,
    VOLUME_TOTAL_VEICULOS DESC;

COMMENT ON TABLE VW_VOLUME_VELOCIDADE_POR_HORA IS 
'Volume de veículos e velocidade média por hora, ranqueado por Estado, Cidade e Bairro - Pergunta 4';

-- ========================================
-- TESTES
-- ========================================

-- Teste 1: Volume por hora em um dia específico
SELECT 
    NR_HORA,
    NM_ESTADO,
    NM_CIDADE,
    NM_BAIRRO,
    VOLUME_TOTAL_VEICULOS,
    VELOCIDADE_MEDIA,
    RANKING_HORA
FROM VW_VOLUME_VELOCIDADE_POR_HORA
WHERE DT_REFERENCIA = DATE '2025-11-01'
ORDER BY RANKING_HORA
FETCH FIRST 20 ROWS ONLY;

-- Teste 2: Top 10 por Estado
SELECT 
    NM_ESTADO,
    NM_CIDADE,
    NM_BAIRRO,
    SUM(VOLUME_TOTAL_VEICULOS) AS TOTAL_VEICULOS,
    ROUND(AVG(VELOCIDADE_MEDIA), 2) AS VEL_MEDIA
FROM VW_VOLUME_VELOCIDADE_POR_HORA
GROUP BY NM_ESTADO, NM_CIDADE, NM_BAIRRO
ORDER BY TOTAL_VEICULOS DESC
FETCH FIRST 10 ROWS ONLY;

-- Teste 3: Por hora do dia (agregado)
SELECT 
    NR_HORA,
    SUM(VOLUME_TOTAL_VEICULOS) AS TOTAL_VEICULOS,
    ROUND(AVG(VELOCIDADE_MEDIA), 2) AS VEL_MEDIA,
    SUM(QTD_INFRACOES) AS TOTAL_INFRACOES
FROM VW_VOLUME_VELOCIDADE_POR_HORA
GROUP BY NR_HORA
ORDER BY NR_HORA;



-- ========================================
-- PERGUNTA 5: Penalidades por Condição da Pista
-- ========================================

CREATE OR REPLACE VIEW VW_PENALIDADES_POR_CONDICAO_PISTA AS
SELECT 
    -- Condição da Pista
    cp.TP_COND_PISTA,
    
    -- Agrupamento por Local (Pergunta 1)
    l.NM_ESTADO,
    l.SG_ESTADO,
    l.NM_CIDADE,
    l.NM_BAIRRO,
    l.NR_QUADRANTE,
    
    -- Agrupamento por Tempo (Pergunta 2)
    t.NR_ANO,
    t.NR_MES,
    t.DS_MES,
    t.DS_DIA_SEMANA,
    t.NR_DIA_SEMANA,
    t.NR_HORA,
    t.DS_DIA_UTIL_FERIADO,
    t.DS_FIM_SEMANA,
    
    -- Clima (complemento)
    c.DS_CLIMA,
    c.TP_TEMPERATURA,
    
    -- RESPOSTA: Penalidades por condição da pista
    COUNT(*) AS QTD_PENALIDADES,
    
    -- Métricas Adicionais
    SUM(f.VL_MULTA) AS VL_TOTAL_MULTAS,
    AVG(f.VL_MULTA) AS VL_MEDIO_MULTAS,
    SUM(f.QT_INFRACOES) AS TOTAL_INFRACOES,
    COUNT(DISTINCT f.SK_ID_VEICULO) AS QTD_VEICULOS_DISTINTOS,
    AVG(f.VL_VELOCIDADE_REGISTRADA) AS VELOCIDADE_MEDIA,
    MIN(f.VL_VELOCIDADE_REGISTRADA) AS VELOCIDADE_MIN,
    MAX(f.VL_VELOCIDADE_REGISTRADA) AS VELOCIDADE_MAX,
    
    -- Rankings
    RANK() OVER (ORDER BY COUNT(*) DESC) AS RANKING_GERAL,
    RANK() OVER (PARTITION BY cp.TP_COND_PISTA ORDER BY COUNT(*) DESC) AS RANKING_POR_CONDICAO
    
FROM 
    TB_FATO_TRAFEGO f
    INNER JOIN TB_DIM_COND_PISTA cp ON f.SK_ID_COND_PISTA = cp.SK_ID_COND_PISTA
    INNER JOIN TB_DIM_LOCAL l ON f.SK_ID_LOCAL = l.SK_ID_LOCAL
    INNER JOIN TB_DIM_TEMPO t ON f.SK_ID_TEMPO = t.SK_ID_TEMPO
    INNER JOIN TB_DIM_CLIMA c ON f.SK_ID_CLIMA = c.SK_ID_CLIMA
WHERE 
    f.ST_INFRACOES = 'ATIVO'
    AND f.ST_REGISTRO_ATUAL = 'A'
    AND cp.ST_REGISTRO_ATUAL = 'A'
    AND l.ST_REGISTRO_ATUAL = 'A'
    AND t.ST_REGISTRO_ATUAL = 'A'
    AND c.ST_REGISTRO_ATUAL = 'A'
GROUP BY 
    cp.TP_COND_PISTA,
    l.NM_ESTADO,
    l.SG_ESTADO,
    l.NM_CIDADE,
    l.NM_BAIRRO,
    l.NR_QUADRANTE,
    t.NR_ANO,
    t.NR_MES,
    t.DS_MES,
    t.DS_DIA_SEMANA,
    t.NR_DIA_SEMANA,
    t.NR_HORA,
    t.DS_DIA_UTIL_FERIADO,
    t.DS_FIM_SEMANA,
    c.DS_CLIMA,
    c.TP_TEMPERATURA
ORDER BY 
    cp.TP_COND_PISTA,
    QTD_PENALIDADES DESC;

COMMENT ON TABLE VW_PENALIDADES_POR_CONDICAO_PISTA IS 
'Penalidades por condição da pista com todos os agrupamentos - Pergunta 5';

-- ========================================
-- TESTES
-- ========================================

-- Teste 1: Resumo por Condição da Pista
SELECT 
    TP_COND_PISTA,
    SUM(QTD_PENALIDADES) AS TOTAL_PENALIDADES,
    SUM(VL_TOTAL_MULTAS) AS TOTAL_MULTAS,
    ROUND(AVG(VELOCIDADE_MEDIA), 2) AS VEL_MEDIA
FROM VW_PENALIDADES_POR_CONDICAO_PISTA
GROUP BY TP_COND_PISTA
ORDER BY TOTAL_PENALIDADES DESC;

-- Teste 2: Por Condição e Local
SELECT 
    TP_COND_PISTA,
    NM_ESTADO,
    NM_CIDADE,
    SUM(QTD_PENALIDADES) AS TOTAL_PENALIDADES
FROM VW_PENALIDADES_POR_CONDICAO_PISTA
GROUP BY TP_COND_PISTA, NM_ESTADO, NM_CIDADE
ORDER BY TOTAL_PENALIDADES DESC
FETCH FIRST 20 ROWS ONLY;

-- Teste 3: Por Condição e Tempo
SELECT 
    TP_COND_PISTA,
    NR_HORA,
    DS_DIA_SEMANA,
    SUM(QTD_PENALIDADES) AS TOTAL_PENALIDADES
FROM VW_PENALIDADES_POR_CONDICAO_PISTA
GROUP BY TP_COND_PISTA, NR_HORA, DS_DIA_SEMANA, NR_DIA_SEMANA
ORDER BY TOTAL_PENALIDADES DESC
FETCH FIRST 20 ROWS ONLY;

-- Teste 4: Por Condição, Clima e Quadrante
SELECT 
    TP_COND_PISTA,
    DS_CLIMA,
    NR_QUADRANTE,
    SUM(QTD_PENALIDADES) AS TOTAL_PENALIDADES
FROM VW_PENALIDADES_POR_CONDICAO_PISTA
GROUP BY TP_COND_PISTA, DS_CLIMA, NR_QUADRANTE
ORDER BY TOTAL_PENALIDADES DESC;




-- ========================================
-- PERGUNTA 6: Tipos de Veículos que Sofrem Mais Penalizações
-- ========================================

CREATE OR REPLACE VIEW VW_VEICULOS_MAIS_PENALIZADOS AS
SELECT 
    -- Tipo de Veículo (RESPOSTA PRINCIPAL)
    v.DS_VEICULO,
    
    -- Detalhes do Veículo
    v.NM_MARCA,
    v.NM_MODELO,
    v.TP_PLACA,
    v.FG_PLACA_ESTRANGEIRA,
    v.PS_ORIGEM_PLACA,
    
    -- RESPOSTA: Quantidade de Penalizações
    COUNT(*) AS QTD_PENALIZACOES,
    
    -- Métricas Adicionais
    SUM(f.VL_MULTA) AS VL_TOTAL_MULTAS,
    AVG(f.VL_MULTA) AS VL_MEDIO_MULTAS,
    SUM(f.QT_INFRACOES) AS TOTAL_INFRACOES,
    AVG(f.VL_VELOCIDADE_REGISTRADA) AS VELOCIDADE_MEDIA_INFRACOES,
    AVG(f."VL_VELOCIDADE_PERMITIDA_KM/H") AS VELOCIDADE_MEDIA_PERMITIDA,
    COUNT(DISTINCT f.SK_ID_LOCAL) AS QTD_LOCAIS_DISTINTOS,
    COUNT(DISTINCT f.SK_ID_RADAR) AS QTD_RADARES_DISTINTOS,
    MAX(f.VL_MULTA) AS VL_MAIOR_MULTA,
    
    -- Rankings
    RANK() OVER (ORDER BY COUNT(*) DESC) AS RANKING_PENALIZACOES,
    RANK() OVER (ORDER BY SUM(f.VL_MULTA) DESC) AS RANKING_VALOR_MULTAS,
    RANK() OVER (PARTITION BY v.DS_VEICULO ORDER BY COUNT(*) DESC) AS RANKING_POR_TIPO,
    
    -- Percentuais
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (), 2) AS PERCENTUAL_TOTAL
    
FROM 
    TB_FATO_TRAFEGO f
    INNER JOIN TB_DIM_VEICULO v ON f.SK_ID_VEICULO = v.SK_ID_VEICULO
WHERE 
    f.ST_INFRACOES = 'ATIVO'
    AND f.ST_VEICULO = 'ATIVO'
    AND f.ST_REGISTRO_ATUAL = 'A'
    AND v.ST_REGISTRO_ATUAL = 'A'
GROUP BY 
    v.DS_VEICULO,
    v.NM_MARCA,
    v.NM_MODELO,
    v.TP_PLACA,
    v.FG_PLACA_ESTRANGEIRA,
    v.PS_ORIGEM_PLACA
ORDER BY 
    QTD_PENALIZACOES DESC,
    VL_TOTAL_MULTAS DESC;

COMMENT ON TABLE VW_VEICULOS_MAIS_PENALIZADOS IS 
'Tipos de veículos que sofrem mais penalizações - Pergunta 6';

-- ========================================
-- TESTES
-- ========================================

-- Teste 1: Resumo por Tipo de Veículo
SELECT 
    DS_VEICULO,
    SUM(QTD_PENALIZACOES) AS TOTAL_PENALIZACOES,
    SUM(VL_TOTAL_MULTAS) AS TOTAL_MULTAS,
    ROUND(AVG(VELOCIDADE_MEDIA_INFRACOES), 2) AS VEL_MEDIA
FROM VW_VEICULOS_MAIS_PENALIZADOS
GROUP BY DS_VEICULO
ORDER BY TOTAL_PENALIZACOES DESC;

-- Teste 2: Top 20 Veículos Mais Penalizados
SELECT 
    DS_VEICULO,
    NM_MARCA,
    NM_MODELO,
    QTD_PENALIZACOES,
    VL_TOTAL_MULTAS,
    RANKING_PENALIZACOES,
    PERCENTUAL_TOTAL
FROM VW_VEICULOS_MAIS_PENALIZADOS
WHERE ROWNUM <= 20
ORDER BY RANKING_PENALIZACOES;

-- Teste 3: Veículos Estrangeiros vs Nacionais
SELECT 
    FG_PLACA_ESTRANGEIRA,
    TP_PLACA,
    COUNT(DISTINCT NM_MARCA || NM_MODELO) AS QTD_MODELOS,
    SUM(QTD_PENALIZACOES) AS TOTAL_PENALIZACOES,
    SUM(VL_TOTAL_MULTAS) AS TOTAL_MULTAS
FROM VW_VEICULOS_MAIS_PENALIZADOS
GROUP BY FG_PLACA_ESTRANGEIRA, TP_PLACA
ORDER BY TOTAL_PENALIZACOES DESC;

-- Teste 4: Por Marca
SELECT 
    DS_VEICULO,
    NM_MARCA,
    SUM(QTD_PENALIZACOES) AS TOTAL_PENALIZACOES,
    SUM(VL_TOTAL_MULTAS) AS TOTAL_MULTAS,
    ROUND(AVG(VELOCIDADE_MEDIA_INFRACOES), 2) AS VEL_MEDIA
FROM VW_VEICULOS_MAIS_PENALIZADOS
GROUP BY DS_VEICULO, NM_MARCA
ORDER BY TOTAL_PENALIZACOES DESC
FETCH FIRST 15 ROWS ONLY;