@C:\Users\rodri\Desktop\Projeto_DW_DBURGER\apaga.sql

@C:\Users\rodri\Desktop\Projeto_DW_DBURGER\cria.sql

-- Gerado por Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   em:        2025-08-25 22:21:16 BRT
--   site:      Oracle Database 11g
--   tipo:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE DB_DIM_CLIENTE 
    ( 
     SK_CLIENTE              NUMBER  NOT NULL , 
     NM_CLIENTE              VARCHAR2 (160)  NOT NULL , 
     NR_CLIENTE_ORIGEM_DADOS NUMBER (10)  NOT NULL , 
     NR_ESTRELAS             NUMBER (10)  NOT NULL , 
     NM_SEXO_CLIENTE         VARCHAR2 (15)  NOT NULL , 
     SG_ESTADO               VARCHAR2 (2)  NOT NULL , 
     NM_ESTADO               VARCHAR2 (30)  NOT NULL , 
     NM_CIDADE               VARCHAR2 (60)  NOT NULL , 
     NM_BAIRRO               VARCHAR2 (45)  NOT NULL , 
     NM_LOGRADOURO           VARCHAR2 (160)  NOT NULL , 
     NR_CLIENTE_ORIGEM       NUMBER (10) , 
     NR_LOTE_CARGA           NUMBER (10) , 
     CPF                     VARCHAR2 (14) , 
     DS_ORIGEM_DOS_DADOS     VARCHAR2 (40)  NOT NULL 
    ) 
;

COMMENT ON COLUMN DB_DIM_CLIENTE.SK_CLIENTE IS 'ESTÁ CHAVE IRÁ ARMAZENAR A CHAVE SURROGATE DA DIMENSÃO CLIENTE.
ESTE ATRIBUTO SERÁ PREENCHIDO AUTOMATICAMENTE INTERNAMENTE PELA CARGA DE DADOS.' 
;

COMMENT ON COLUMN DB_DIM_CLIENTE.NM_CLIENTE IS 'ESTE ATRIBUTO IRÁ ARMAZENAR O NOME DO CLIENTE' 
;

COMMENT ON COLUMN DB_DIM_CLIENTE.NR_CLIENTE_ORIGEM_DADOS IS 'ESTE ATRIBUTO IRÁ ARMAZENAR O CÓDIGO DO CLIENTE NA ORIGEM DOS DADOS.
ESTE ATRIBUTO É OBRIGATÓRIO E SERÁ UTILIZADO PARA CRIAR RASTREABILIDADE COM OS DADOS DE ORIGEM.' 
;

COMMENT ON COLUMN DB_DIM_CLIENTE.NR_ESTRELAS IS 'ESTE ATRIBUTO IRÁ ARMAZENAR O NÚMERO DE ESTRELAS DO CLIENTE.
ESTE ATRIBUTO É OBRIGATÓRIO E PODEMOS ARMAZENAR OS NÚMEROS ENTRE 1 E 5.
ONDE 1 SIMBOLIZA A BAIXA FIDELIDADE E 5 ALTA FIDELIDADE.' 
;

COMMENT ON COLUMN DB_DIM_CLIENTE.NM_SEXO_CLIENTE IS 'ESTE ATRIBUTO IRÁ ARMAZENAR O SEXO DO CLIENTE.
ESTE ATRIBUTO É OBRIGATÓRIO E PODEMOS ARMAZENAR OS DADOS DA ORIENTAÇÃO SEXUAL, OU COMO O CLIENTE SE IDENTIFICA.' 
;

COMMENT ON COLUMN DB_DIM_CLIENTE.SG_ESTADO IS 'ESTÁ CHAVE IRÁ ARMAZENAR A DO ESTADO DO CLIENTE.
SEU CONTEÚDO IRÁ ARMAZENAR TODAS AS SIGLAS DO ESTADO DO CLIENTE EXISTENTES.' 
;

COMMENT ON COLUMN DB_DIM_CLIENTE.NM_ESTADO IS 'ESTÁ CHAVE IRÁ ARMAZENAR O NOME DO ESTADO DO CLIENTE.
SEU CONTEÚDO IRÁ ARMAZENAR O NOME DE TODOS OS ESTADOS ONDE HAJAM CLIENTE..' 
;

COMMENT ON COLUMN DB_DIM_CLIENTE.NM_CIDADE IS 'ESTÁ CHAVE IRÁ ARMAZENAR O NOME DA CIDADE DO CLIENTE.
SEU CONTEÚDO IRÁ ARMAZENAR O NOME DE TODAS AS CIDADES ONDE HAJAM CLIENTE..' 
;

COMMENT ON COLUMN DB_DIM_CLIENTE.NM_BAIRRO IS 'ESTÁ CHAVE IRÁ ARMAZENAR O NOME DO BAIRRO DO CLIENTE.
SEU CONTEÚDO IRÁ ARMAZENAR O NOME DE TODOS OS BAIRROS ONDE HAJAM CLIENTE..' 
;

COMMENT ON COLUMN DB_DIM_CLIENTE.NM_LOGRADOURO IS 'ESTÁ CHAVE IRÁ ARMAZENAR O NOME DA RUA E CPMPLEMENTOS DO ENDEREÇO  DO CLIENTE.
SEU CONTEÚDO IRÁ ARMAZENAR O NOME DE TODOS OS LOGRADOUROS ONDE HAJAM CLIENTE..' 
;

ALTER TABLE DB_DIM_CLIENTE 
    ADD CONSTRAINT DB_SK_DIM_CLIENTE PRIMARY KEY ( SK_CLIENTE ) ;



-- Relatório do Resumo do Oracle SQL Developer Data Modeler: 
-- 
-- CREATE TABLE                             1
-- CREATE INDEX                             0
-- ALTER TABLE                              1
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
