-- Gerado por Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   em:        2025-09-24 13:49:20 BRT
--   site:      Oracle Database 11g
--   tipo:      Oracle Database 11g



DROP TABLE TB_DIM_ANIMAL CASCADE CONSTRAINTS 
;

DROP TABLE TB_DIM_LOJA CASCADE CONSTRAINTS 
;

DROP TABLE TB_DIM_PESSOA CASCADE CONSTRAINTS 
;

DROP TABLE TB_DIM_TEMPO CASCADE CONSTRAINTS 
;

DROP TABLE TB_FTO_CONSULTA CASCADE CONSTRAINTS 

