--VIEWS

--LOJA

SELECT *
FROM V_FATURAMENTO_LOJA;

--VIEW

CREATE OR REPLACE VIEW V_FATURAMENTO_LOJA AS
SELECT
    L.NM_LOJA AS NOME_LOJA,
    L.NM_CIDADE AS CIDADE_LOJA,
    L.SG_ESTADO AS ESTADO_UF_LOJA,
    COUNT(C.NR_CONSULTA) AS TOTAL_CONSULTAS_UNICAS,
    SUM(C.VL_TOTAL_CONSULTA) AS FATURAMENTO_TOTAL_LOJA,
    SUM(CASE WHEN C.ST_CONSULTA = 'Realizada' THEN C.VL_TOTAL_CONSULTA ELSE 0 END) AS FATURAMENTO_LOJA_REALIZADO,
    SUM(CASE WHEN C.ST_CONSULTA = 'Cancelada' THEN C.VL_TOTAL_CONSULTA ELSE 0 END) AS FATURAMENTO_LOJA_CANCELADO,
    SUM(CASE WHEN C.ST_CONSULTA = 'Agendada' THEN C.VL_TOTAL_CONSULTA ELSE 0 END) AS FATURAMENTO_LOJA_AGENDADO,
    AVG(C.VL_TOTAL_CONSULTA) AS TICKET_MEDIO_LOJA
FROM
    TB_DIM_LOJA L
JOIN (
    SELECT DISTINCT -- Garante que cada consulta é contada uma única vez pelo seu valor total
        FC.NR_CONSULTA,
        FC.VL_TOTAL_CONSULTA,
        FC.ST_CONSULTA,
        FC.SK_ID_LOJA
    FROM
        TB_FTO_CONSULTA FC
) C ON L.SK_ID_LOJA = C.SK_ID_LOJA
GROUP BY
    L.NM_LOJA,
    L.NM_CIDADE,
    L.SG_ESTADO;
	
	
--CONSULTA
SELECT *
FROM V_CONSULTAS_DETALHADAS;

--VIEW

CREATE OR REPLACE VIEW V_CONSULTAS_DETALHADAS AS
SELECT
    FC.NR_CONSULTA,
    FC.NR_ITEM_CONSULTA,
    FC.ST_ITEM_SERVICO,
    FC.VL_UNIT_SERVICO,
    FC.QT_SERVICO,
    (FC.VL_UNIT_SERVICO * FC.QT_SERVICO) AS VALOR_BRUTO_ITEM,
    FC.VL_DESCONTO AS DESCONTO_ITEM,
    (FC.VL_UNIT_SERVICO * FC.QT_SERVICO - FC.VL_DESCONTO) AS VALOR_LIQUIDO_ITEM,
    FC.VL_TOTAL_CONSULTA AS VALOR_TOTAL_CONSULTA_GERAL, -- Valor total da consulta (pode ser repetido por item)
    FC.ST_CONSULTA AS STATUS_CONSULTA,
    FC.DS_DESCONTO AS TIPO_DESCONTO_CONSULTA,
    FC.NM_FONTE_DADOS,

    P.NM_PESSOA AS NOME_CLIENTE,
    P.NR_CPF AS CPF_CLIENTE,
    P.DS_EMAIL AS EMAIL_CLIENTE,
    P.DS_SEXO_PESSOA AS SEXO_CLIENTE,
    P.DS_ESTADO_CIVIL AS ESTADO_CIVIL_CLIENTE,
    P.NM_CIDADE AS CIDADE_CLIENTE,
    P.SG_ESTADO AS ESTADO_UF_CLIENTE,
    P.DT_NASCIMENTO AS DATA_NASCIMENTO_CLIENTE,

    L.NM_LOJA AS NOME_LOJA,
    L.NR_LOJA AS NUMERO_LOJA,
    L.DS_LOGRADOURO AS LOGRADOURO_LOJA,
    L.NM_BAIRRO AS BAIRRO_LOJA,
    L.NM_CIDADE AS CIDADE_LOJA,
    L.SG_ESTADO AS ESTADO_UF_LOJA,
    L.DT_FUNDACAO AS DATA_FUNDACAO_LOJA,
    L.IM_SOBRE_SERVICO AS IMPOSTO_SOBRE_SERVICO_LOJA,

    A.DS_ESPECIE AS ESPECIE_ANIMAL,
    A.DS_RACA AS RACA_ANIMAL,
    A.DT_NASCIMENTO_ANIMAL AS DATA_NASCIMENTO_ANIMAL,

    T.DT_REFERENCIA AS DATA_CONSULTA,
    T.DS_DATA_EXTENSO AS DATA_EXTENSO_CONSULTA,
    T.NR_ANO AS ANO_CONSULTA,
    T.NR_MES AS MES_NUMERO_CONSULTA,
    T.DS_MES_ANO AS MES_ANO_CONSULTA,
    T.NR_TRIMESTRE AS TRIMESTRE_NUMERO_CONSULTA,
    T.DS_TRIMESTRE_ANO AS TRIMESTRE_ANO_CONSULTA,
    T.NR_SEMESTRE AS SEMESTRE_NUMERO_CONSULTA,
    T.DS_SEMESTRE_ANO AS SEMESTRE_ANO_CONSULTA,
    T.NR_DIA_SEMANA AS DIA_SEMANA_NUMERO,
    T.DS_DIA_UTIL_FERIADO AS INDICADOR_DIA_UTIL_FERIADO,
    T.DS_FIM_SEMANA AS INDICADOR_FIM_SEMANA,
    T.NR_HORA AS HORA_CONSULTA
FROM
    TB_FTO_CONSULTA FC
JOIN
    TB_DIM_PESSOA P ON FC.SK_ID_PESSOA = P.SK_ID_PESSOA
JOIN
    TB_DIM_LOJA L ON FC.SK_ID_LOJA = L.SK_ID_LOJA
JOIN
    TB_DIM_ANIMAL A ON FC.SK_ID_ANIMAL = A.SK_ID_ANIMAL
JOIN
    TB_DIM_TEMPO T ON FC.SK_ID_TEMPO = T.SK_ID_TEMPO;
	
	
	

--CLIENTE

SELECT
    NOME_CLIENTE,
    CPF_CLIENTE,
    IDADE_CLIENTE,
    VALOR_TOTAL_GASTO_CLIENTE,
    QUANTIDADE_CONSULTAS_UNICAS
FROM V_PERFIL_CONSUMO_CLIENTE
ORDER BY VALOR_TOTAL_GASTO_CLIENTE DESC;

--VIEW

CREATE OR REPLACE VIEW V_PERFIL_CONSUMO_CLIENTE AS
SELECT
    P.NM_PESSOA AS NOME_CLIENTE,
    P.NR_CPF AS CPF_CLIENTE,
    P.DS_EMAIL AS EMAIL_CLIENTE,
    P.DT_NASCIMENTO AS DATA_NASCIMENTO_CLIENTE,
    (EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM P.DT_NASCIMENTO)) AS IDADE_CLIENTE,
    P.DS_SEXO_PESSOA AS SEXO_CLIENTE,
    P.DS_ESTADO_CIVIL AS ESTADO_CIVIL_CLIENTE,
    P.NM_CIDADE AS CIDADE_CLIENTE,
    P.SG_ESTADO AS ESTADO_UF_CLIENTE,
    P.ST_PESSOA AS STATUS_CLIENTE,
    COUNT(C.NR_CONSULTA) AS QUANTIDADE_CONSULTAS_UNICAS,
    SUM(C.VL_TOTAL_CONSULTA) AS VALOR_TOTAL_GASTO_CLIENTE,
    AVG(C.VL_TOTAL_CONSULTA) AS TICKET_MEDIO_POR_CONSULTA_CLIENTE,
    MAX(T.DT_REFERENCIA) AS ULTIMA_DATA_CONSULTA,
    MIN(T.DT_REFERENCIA) AS PRIMEIRA_DATA_CONSULTA
FROM
    TB_DIM_PESSOA P
JOIN (
    SELECT DISTINCT -- Garante que cada consulta é contada uma única vez pelo seu valor total
        FC.NR_CONSULTA,
        FC.VL_TOTAL_CONSULTA,
        FC.SK_ID_PESSOA,
        FC.SK_ID_TEMPO
    FROM
        TB_FTO_CONSULTA FC
) C ON P.SK_ID_PESSOA = C.SK_ID_PESSOA
JOIN
    TB_DIM_TEMPO T ON C.SK_ID_TEMPO = T.SK_ID_TEMPO
GROUP BY
    P.NM_PESSOA,
    P.NR_CPF,
    P.DS_EMAIL,
    P.DT_NASCIMENTO,
    P.DS_SEXO_PESSOA,
    P.DS_ESTADO_CIVIL,
    P.NM_CIDADE,
    P.SG_ESTADO,
    P.ST_PESSOA;
	
	
	
--ANIMAIS

SELECT
    ESPECIE_ANIMAL,
    RACA_ANIMAL,
    ANO_CONSULTA,
    MES_ANO_CONSULTA,
    QUANTIDADE_SERVICOS_PRESTADOS,
    RECEITA_LIQUIDA_ITENS_SERVICO
FROM V_ANALISE_SERVICOS_ANIMAIS
WHERE ESPECIE_ANIMAL = 'Canina'
  AND ANO_CONSULTA = 2024
ORDER BY RECEITA_LIQUIDA_ITENS_SERVICO DESC;


--VIEW

CREATE OR REPLACE VIEW V_ANALISE_SERVICOS_ANIMAIS AS
SELECT
    A.DS_ESPECIE AS ESPECIE_ANIMAL,
    A.DS_RACA AS RACA_ANIMAL,
    T.NR_ANO AS ANO_CONSULTA,
    T.DS_MES_ANO AS MES_ANO_CONSULTA,
    COUNT(FC.NR_ITEM_CONSULTA) AS TOTAL_ITENS_SERVICO_VENDIDOS,
    SUM(FC.QT_SERVICO) AS QUANTIDADE_SERVICOS_PRESTADOS,
    SUM(FC.VL_UNIT_SERVICO * FC.QT_SERVICO) AS VALOR_BRUTO_ITENS_SERVICO,
    SUM(FC.VL_DESCONTO) AS TOTAL_DESCONTO_APLICADO_ITENS,
    SUM(FC.VL_UNIT_SERVICO * FC.QT_SERVICO - FC.VL_DESCONTO) AS RECEITA_LIQUIDA_ITENS_SERVICO
FROM
    TB_FTO_CONSULTA FC
JOIN
    TB_DIM_ANIMAL A ON FC.SK_ID_ANIMAL = A.SK_ID_ANIMAL
JOIN
    TB_DIM_TEMPO T ON FC.SK_ID_TEMPO = T.SK_ID_TEMPO
WHERE
    FC.ST_CONSULTA = 'Realizada' -- Foca apenas em serviços que foram realmente executados
GROUP BY
    A.DS_ESPECIE,
    A.DS_RACA,
    T.NR_ANO,
    T.DS_MES_ANO
ORDER BY
    ANO_CONSULTA, MES_ANO_CONSULTA, ESPECIE_ANIMAL, RACA_ANIMAL;
	
	
	
	
--TEMPO

SELECT
    ANO,
    MES_ANO,
    QTD_CONSULTAS_REALIZADAS,
    FATURAMENTO_REALIZADO_PERIODO
FROM V_CONSULTAS_TEMPORAIS
WHERE QTD_CONSULTAS_REALIZADAS > 0 -- Opcional: para mostrar apenas meses com consultas realizadas
ORDER BY ANO ASC, MES_ANO ASC;


--VIEW

CREATE OR REPLACE VIEW V_CONSULTAS_TEMPORAIS AS
SELECT
    T.NR_ANO AS ANO,
    T.DS_SEMESTRE_ANO AS SEMESTRE,
    T.DS_TRIMESTRE_ANO AS TRIMESTRE,
    T.DS_MES_ANO AS MES_ANO,
    T.DS_DIA_UTIL_FERIADO AS DIA_UTIL_FERIADO,
    T.DS_FIM_SEMANA AS FIM_SEMANA,
    COUNT(C.NR_CONSULTA) AS TOTAL_CONSULTAS_UNICAS,
    SUM(C.VL_TOTAL_CONSULTA) AS FATURAMENTO_TOTAL_PERIODO,
    SUM(CASE WHEN C.ST_CONSULTA = 'Realizada' THEN C.VL_TOTAL_CONSULTA ELSE 0 END) AS FATURAMENTO_REALIZADO_PERIODO,
    COUNT(CASE WHEN C.ST_CONSULTA = 'Realizada' THEN C.NR_CONSULTA ELSE NULL END) AS QTD_CONSULTAS_REALIZADAS,
    COUNT(CASE WHEN C.ST_CONSULTA = 'Cancelada' THEN C.NR_CONSULTA ELSE NULL END) AS QTD_CONSULTAS_CANCELADAS,
    COUNT(CASE WHEN C.ST_CONSULTA = 'Agendada' THEN C.NR_CONSULTA ELSE NULL END) AS QTD_CONSULTAS_AGENDADAS
FROM
    TB_DIM_TEMPO T
JOIN (
    SELECT DISTINCT -- Garante que cada consulta é contada uma única vez pelo seu valor total
        FC.NR_CONSULTA,
        FC.VL_TOTAL_CONSULTA,
        FC.ST_CONSULTA,
        FC.SK_ID_TEMPO
    FROM
        TB_FTO_CONSULTA FC
) C ON T.SK_ID_TEMPO = C.SK_ID_TEMPO
GROUP BY
    T.NR_ANO,
    T.DS_SEMESTRE_ANO,
    T.DS_TRIMESTRE_ANO,
    T.DS_MES_ANO,
    T.DS_DIA_UTIL_FERIADO,
    T.DS_FIM_SEMANA
ORDER BY
    ANO, MES_ANO, SEMESTRE, TRIMESTRE;
	
	

